// (c) 2021 Opendoor Labs Inc.
// This code is licenced under the MIT licence (see the LICENCE file in the repo root).
package test

import (
	// just make sure that the module generated by an empty config
	// file compiles
	_ "github.com/opendoor-labs/pggen/cmd/pggen/test/empty_models"
)
