name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        entrypoint: [ "test13", "test12", "test11", "test10", "test9_6", "test9_5", "lint" ]

    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build -t pggen_source .
      - name: Running Step ${{ matrix.entrypoint }}
        run: docker-compose --file .github/docker-compose.yml run ${{ matrix.entrypoint }}

  # msgv gets a seperate one since it uses its own entrypoint
  msgv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build -t pggen_source_msgv -f Dockerfile.msgv .
      - name: Use Postgres ${{ matrix.postgres-version }}
        run: docker-compose --file .github/docker-compose.yml run msgv
